
services:
  ph_sites:
    restart: always
    # container_name: ph_sites
    container_name: ph_sites_${ENV_NAME}
    image: nginx
    expose:
      - "80"
    volumes:
      - ./dst:/var/www/html/
      - ./compose/config/nginx/default.conf:/etc/nginx/conf.d/default.conf

    environment:
      VIRTUAL_HOST:
        ${IPACS_DOMAIN_NAME},
        ${CAP_DOMAIN_NAME},
        ${CONF_DOMAIN_NAME},
        ${ALBUM_DOMAIN_NAME}, 
    # env_file:
    #   - ./development.env
    # environment:
    #   VIRTUAL_HOST:
    #     physcon.my, physcon.ru,
    #     cap.physcon.my, cap.physcon.ru,
    #     conf.physcon.my, conf.physcon.ru,
    #     album.physcon.my, album.physcon.ru,
    networks:
      - frontend


networks:
  frontend:
    external: true
    name: frontend


