
services:
  ph_sites:
    container_name: ph_sites
    image: nginx
    expose:
      - "80"
    volumes:
      - ./dst:/var/www/html/
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      VIRTUAL_HOST:
        physcon.my, physcon.ru,
        cap.physcon.my, cap.physcon.ru,
        conf.physcon.my, conf.physcon.ru,
        album.physcon.my, album.physcon.ru,
    networks:
      - frontend


networks:
  frontend:
    external: true
    name: frontend


