# baseURL = 'https://example.org/'
# languageCode = 'en-us'
title = 'International Physics and Control Society (IPACS)'
# theme = 'ananke'

# copyright = 'The Laboratory "Control of Complex Systems", IPME RAS'



#publishDir = '../publish'

contentDir = "sites/ipacs/content"
publishDir = "public/ipacs"


[params]
    # copyrightURL = 'https://www.ipme.ru/ipme/labs/ccs/'
    currentSiteId = 'ipacs'

# sectionPagesMenu = 'main'


[menus]
  [[menus.main]]
    # name = 'Main page'
    name = 'Main'
    pageRef = '/'
    weight = 10
  [[menus.main]]
    name = 'News'
    pageRef = '/news'
    weight = 20
  [[menus.main]]
    name = 'About IPACS'
    pageRef = '/about'
    weight = 30
  [[menus.main]]
    name = 'Regulations'
    pageRef = '/regulations'
    weight = 40
  [[menus.main]]
    name = 'Membership'
    pageRef = '/membership'
    weight = 50
  [[menus.main]]
    name = 'IPACS Officials'
    pageRef = '/officials'
    weight = 60
  [[menus.main]]
    name = 'Contacts'
    pageRef = '/contacts'
    weight = 70


  # [[menus.external]]
  #   name = 'Submit Online'
  #   url = 'http://coms.physcon.ru/conf/1635/'
  #   weight = 50
  # [[menus.external]]
  #   name = 'Read Online'
  #   url = 'http://lib.physcon.ru/doc?id=29e59dce4f11'
  #   weight = 60



