# baseURL = 'https://example.org/'
# languageCode = 'en-us'
title = 'CYBERNETICS AND PHYSICS Open Access Journal'
# theme = 'ananke'

# copyright = 'The Laboratory "Control of Complex Systems", IPME RAS'


contentDir = "sites/cap/content"
publishDir = "public/cap"


disablePathToLower = true


[params]
    # copyrightURL = 'https://www.ipme.ru/ipme/labs/ccs/'
    currentSiteId = 'cap'



[menus]
  [[menus.main]]
    # name = 'Main page'
    name = 'Main'
    pageRef = '/'
    weight = 10
  [[menus.main]]
    # name = 'Aims and Scope'
    name = 'Scope'
    # title = 'Aims and Scope'
    pageRef = '/scope'
    weight = 20
    # pre = '<i class="fa-solid fa-code"></i>'
  [[menus.main]]
    # name = 'Editorial Board'
    name = 'Editorial'
    pageRef = '/editorial'
    weight = 30
  [[menus.main]]
    # name = 'Author Information'
    name = 'For authors'
    pageRef = '/forauthors'
    weight = 40
  [[menus.main]]
    name = 'Contacts'
    pageRef = '/contacts'
    weight = 70


  [[menus.main]]
    name = 'CAP Flyer'
    url = '/cap/CAPjournalinfo.pdf'
    weight = 100
    [menus.main.params]
      class = 'pdf'
  [[menus.main]]
    name = 'Publication Ethics'
    url = '/cap/CAP_Publication_Ethics.pdf'
    weight = 110
    [menus.main.params]
      class = 'pdf'


  [[menus.external]]
    name = 'Submit Online'
    url = 'http://coms.physcon.ru/conf/1635/'
    weight = 50
  [[menus.external]]
    name = 'Read Online'
    url = 'http://lib.physcon.ru/doc?id=29e59dce4f11'
    weight = 60









