# baseURL = 'https://example.org/'
# languageCode = 'en-us'
title = 'PhysCon Album'
# theme = 'ananke'

# copyright = 'The Laboratory "Control of Complex Systems", IPME RAS'



# disableKinds = ["RSS"]



#publishDir = '../publish'

contentDir = "sites/album/content"
staticDir = "sites/album/static"
publishDir = "public/album"

# layoutDir = "layouts"

# uglyURLs = true


[params]
    # copyrightURL = 'https://www.ipme.ru/ipme/labs/ccs/'
    currentSiteId = 'album'


