
help:
	#

build: clean
	hugo -D --config="sites/cap/hugo.toml"
	hugo -D --config="sites/ipacs/hugo.toml"
	hugo -D --config="sites/conf/hugo.toml"
	hugo -D --config="sites/album/hugo.toml"

clean:
	rm -r public/*


