
help:
	#

build: clean
	hugo -D --config="hugo.toml,sites/cap/hugo.toml"
	hugo -D --config="hugo.toml,sites/ipacs/hugo.toml"
	hugo -D --config="hugo.toml,sites/conf/hugo.toml"
	hugo -D --config="hugo.toml,sites/album/hugo.toml"

clean:
	# rm -r public/*


