# baseURL = 'https://example.org/'
# languageCode = 'en-us'
title = 'PhysCon Conferences'
# theme = 'ananke'

# copyright = 'The Laboratory "Control of Complex Systems", IPME RAS'

# disableKinds = ["RSS"]


contentDir = "sites/conf/content"
staticDir = "sites/conf/static"
publishDir = "public/conf"

# layoutDir = "layouts"

# uglyURLs = true


[params]
    # copyrightURL = 'https://www.ipme.ru/ipme/labs/ccs/'
    currentSiteId = 'conf'


