# baseURL = 'https://example.org/'
# languageCode = 'en-us'
title = 'PhysCon Conferences'
# theme = 'ananke'

# copyright = 'The Laboratory "Control of Complex Systems", IPME RAS'

# disableKinds = ["RSS"]


contentDir = "sites/conf/content"
staticDir = "sites/conf/static"
publishDir = "public/conf"

# layoutDir = "layouts"

# uglyURLs = true


[params]
    # copyrightURL = 'https://www.ipme.ru/ipme/labs/ccs/'
    currentSiteId = 'conf'


# sectionPagesMenu = 'main'



  # [[menus.physcon]]
  #   identifier = 'ipacs'
  #   name = 'IPACS Home'
  #   url = 'http://physcon.my'
  #   title = 'International Physics and Control Society home page'
  #   weight = 10
  # [[menus.physcon]]
  #   identifier = 'coms'
  #   name = 'CoMS'
  #   url = 'http://coms.physcon.my'
  #   title = 'Conference Management System (submission site)'
  #   weight = 20
  # [[menus.physcon]]
  #   identifier = 'cap'
  #   name = 'CAP Journal'
  #   url = 'http://cap.physcon.my'
	# title = 'Cybernetics and Physics Journal'
  #   weight = 30
  # [[menus.physcon]]
  #   identifier = 'lib'
  #   name = 'Library'
  #   url = 'http://lib.physcon.my'
	# title = 'IPACS Electronic library'
  #   weight = 40
  # [[menus.physcon]]
  #   identifier = 'conf'
  #   name = 'Conferences'
  #   url = 'http://conf.physcon.my'
	# title = 'Conferences sites'
  #   weight = 60
  # [[menus.physcon]]
  #   identifier = 'album'
  #   name = 'Album'
  #   url = 'http://album.physcon.my'
	# title = 'Album'
  #   weight = 70









